# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'china_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import *
from PyQt5.QtCore import *
from graphics_drawing import *

class Ui_china_ui(object):

    def setupUi(self, china_ui):
        china_ui.setObjectName("china_ui")
        china_ui.resize(1000, 600)

        self.centralwidget = QtWidgets.QWidget(china_ui)
        self.centralwidget.setObjectName("centralwidget")

        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(40, 10, 110, 22))
        self.dateEdit.setObjectName("dateEdit")

        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(160, 10, 75, 23))
        self.pushButton1.setObjectName("get_time")

        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(245, 10, 75, 23))
        self.pushButton2.setObjectName("refresh")

        self.refreshlebal = QtWidgets.QLabel(self.centralwidget)
        self.refreshlebal.setGeometry((QtCore.QRect(350,10,300,23)))
        self.refreshlebal.setObjectName("refreshlabal")

        self.browser = QWebEngineView(self.centralwidget)
        self.browser.setGeometry(QtCore.QRect(40, 40, 900, 500))
        self.browser.load(QUrl('file:///H:/PYTHON/PythonWork/country.html'))
        self.browser.setObjectName("htmlwindow")

        china_ui.setCentralWidget(self.centralwidget)

        self.pushButton1.clicked.connect(lambda:self.get_time())
        self.pushButton2.clicked.connect(lambda:self.refresh_map())

        self.retranslateUi(china_ui)
        QtCore.QMetaObject.connectSlotsByName(china_ui)

    def retranslateUi(self, china_ui):
        _translate = QtCore.QCoreApplication.translate
        china_ui.setWindowTitle(_translate("china_ui", "中国疫情数据可视化地图"))
        self.pushButton1.setText(_translate("china_ui", "修改时间"))
        self.pushButton2.setText(_translate("china_ui", "刷新"))
        self.refreshlebal.setText(_translate("china_ui","请等候地图加载"))

    def get_time(self):
        datetime = self.dateEdit.dateTime()
        time = datetime.toString("MM-dd-yyyy")
        render_china_map_chart(str(time))
        self.refreshlebal.setText("加载完毕,请刷新")


    def refresh_map(self):
        self.browser.load(QUrl('file:///H:/PYTHON/PythonWork/country.html'))
        self.refreshlebal.setText("请等候地图加载")
