# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from country_ui import *
from china_ui import *
import time
class Ui_window(object):
    app1 = QApplication(sys.argv)
    window1 = QMainWindow()
    ui1 = Ui_china_ui()
    ui1.setupUi(window1)

    app2 = QApplication(sys.argv)
    window2 = QMainWindow()
    ui2 = Ui_country_ui()
    ui2.setupUi(window2)
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(323, 229)
        self.label = QtWidgets.QLabel(window)
        self.label.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.china_button = QtWidgets.QPushButton(window)
        self.china_button.setGeometry(QtCore.QRect(30, 150, 111, 51))
        self.china_button.setObjectName("china_button")
        self.country_button = QtWidgets.QPushButton(window)
        self.country_button.setGeometry(QtCore.QRect(180, 150, 111, 51))
        self.country_button.setObjectName("country_button")
        self.label_2 = QtWidgets.QLabel(window)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(window)
        self.label_3.setGeometry(QtCore.QRect(180, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.china_button.clicked.connect(lambda :self.show_china_ui())
        self.country_button.clicked.connect(lambda :self.show_country_ui())

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def show_china_ui(self):

        self.window1.show()
        self.app1.exec()



    def show_country_ui(self):

        self.window2.show()
        self.app2.exec()


    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "window"))
        self.label.setText(_translate("window", "疫情数据可视化分析软件"))
        self.china_button.setText(_translate("window", "点击查看"))
        self.country_button.setText(_translate("window", "点击查看"))
        self.label_2.setText(_translate("window", "中国疫情地图"))
        self.label_3.setText(_translate("window", "疫情数据折线图"))

if __name__ == '__main__':
    app0 = QApplication(sys.argv)
    Window0 = QMainWindow()
    ui0 = Ui_window()
    ui0.setupUi(Window0)
    Window0.show()
    sys.exit(app0.exec_())

